# Generated by Django 2.1.3 on 2018-11-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='001543561426906ba072579f7e44f52b1790349a15ffdf8000', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0015435614269063fac3ad3a1714fd1a6ecfe082e0d1150000', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='001543561426906212ac3c0f52a4e398866e6b624304639000', max_length=32, primary_key=True, serialize=False),
        ),
    ]
