# Generated by Django 2.1.3 on 2018-11-30 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_blog', '0002_auto_20181130_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gmt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='gmt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gmt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='gmt_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='001543562242698cd0ae44c6ff54120a22bcfa2f775f113000', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='gmt_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='001543562242699ed49b886f02848569ea89edadb3f513f000', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmt_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='00154356224269812fc4460c46f4d16a26fc06e1c2a9e26000', max_length=32, primary_key=True, serialize=False),
        ),
    ]
