# Generated by Django 2.1.3 on 2018-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_blog', '0003_auto_20181130_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='0015435631342422417650ea6b545208269e83feb7594f0000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0015435631342422ebdf8f499d04715b9821423f49b798a000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='0015435631342419c7772f1ff9c4e248f18e71d53ad8f7a000', max_length=50, primary_key=True, serialize=False),
        ),
    ]
