# Generated by Django 2.1.3 on 2018-11-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_blog', '0004_auto_20181130_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='00154356951935053902e654bc14fe186bbb9279968c08e000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0015435695193513a63273651eb48ed90de58376981b647000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='001543569519350ed1562e604584eae9be5333d0f480174000', max_length=50, primary_key=True, serialize=False),
        ),
    ]
