# Generated by Django 2.1.3 on 2018-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_blog', '0005_auto_20181130_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='00154356991510747a9d68168b34464a4c35cae22887fc0000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0015435699151077fc5f2b198254464a906c08e2e28d425000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='0015435699151061334d91ee5af430abeeeb7d34ba41d22000', max_length=50, primary_key=True, serialize=False),
        ),
    ]
